const { wrap } = require('../helpers/response');
const { getDB } = require('../config/database');
const { hasPermission } = require('../middleware/permisos');

function peruDate() {
  const p={}; for(const x of new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()))p[x.type]=x.value;
  return `${p.year}-${p.month}-${p.day}`;
}
function iso(v,f){return /^\d{4}-\d{2}-\d{2}$/.test(String(v||''))?String(v):f;}
function addDays(s,n){const [y,m,d]=s.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d));x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10);}
function span(a,b){return Math.max(1,Math.round((new Date(b+'T00:00:00Z')-new Date(a+'T00:00:00Z'))/86400000)+1);}
async function scope(req){const u=req.session.usuario||{};const global=!!u.es_global&&await hasPermission(req,'dashboard.ver_global');return {global,branch:global?(Number(req.query.sucursal_id)||null):(Number(u.sucursal_id)||null)};}
async function safe(db,sql,params=[],fallback=[]){try{const [rows]=await db.query(sql,params);return rows;}catch(e){console.error('[DASHBOARD PARCIAL]',e.message);return fallback;}}

module.exports={
  resumen:wrap(async(req,res)=>{
    const db=getDB(),today=peruDate(),month=today.slice(0,7)+'-01';let from=iso(req.query.desde,month),to=iso(req.query.hasta,today);if(from>today)from=today;if(to>today)to=today;if(from>to)[from,to]=[to,from];let days=span(from,to);if(days>366){from=addDays(to,-365);days=366;}
    const previousTo=addDays(from,-1),previousFrom=addDays(previousTo,-(days-1));const {global,branch}=await scope(req);const bs=branch?' AND v.sucursal_id=?':'';const bp=branch?[branch]:[];
    const period=(await safe(db,`SELECT COUNT(*) n,COALESCE(SUM(v.total),0) s FROM ventas v WHERE DATE(v.created_at) BETWEEN ? AND ? AND v.estado_venta='registrada'${bs}`,[from,to,...bp],[{n:0,s:0}]))[0]||{n:0,s:0};
    const prev=(await safe(db,`SELECT COUNT(*) n,COALESCE(SUM(v.total),0) s FROM ventas v WHERE DATE(v.created_at) BETWEEN ? AND ? AND v.estado_venta='registrada'${bs}`,[previousFrom,previousTo,...bp],[{n:0,s:0}]))[0]||{n:0,s:0};
    const day=(await safe(db,`SELECT COUNT(*) n,COALESCE(SUM(v.total),0) s FROM ventas v WHERE DATE(v.created_at)=? AND v.estado_venta='registrada'${bs}`,[today,...bp],[{n:0,s:0}]))[0]||{n:0,s:0};
    const productWhere=branch?' AND p.sucursal_id=?':'';
    const product=(await safe(db,`SELECT COUNT(*) n,SUM(p.stock_actual<=p.stock_minimo) low FROM productos p WHERE p.estado=0${productWhere}`,branch?[branch]:[],[{n:0,low:0}]))[0]||{n:0,low:0};
    const clients=(await safe(db,`SELECT COUNT(*) n FROM clientes c WHERE c.activo=1 AND c.es_general=0${branch?' AND c.sucursal_registro_id=?':''}`,branch?[branch]:[],[{n:0}]))[0]||{n:0};
    const pending=(await safe(db,`SELECT COUNT(*) n FROM pedidos_web pw WHERE pw.estado_pago IN ('pendiente','observado','en_verificacion') AND pw.estado_pedido<>'cancelado'${branch?' AND (pw.sucursal_id=? OR pw.es_multisucursal=1)':''}`,branch?[branch]:[],[{n:0}]))[0]||{n:0};
    const seriesRows=await safe(db,`SELECT DATE_FORMAT(v.created_at,'%Y-%m-%d') fecha,COUNT(*) n,COALESCE(SUM(v.total),0) total FROM ventas v WHERE DATE(v.created_at) BETWEEN ? AND ? AND v.estado_venta='registrada'${bs} GROUP BY DATE(v.created_at) ORDER BY DATE(v.created_at)`,[from,to,...bp],[]);const sm=new Map(seriesRows.map(x=>[x.fecha,x]));const series=[];for(let d=from;d<=to&&series.length<366;d=addDays(d,1)){const x=sm.get(d);series.push({fecha:d,n:Number(x?.n||0),total:Number(x?.total||0)});}
    const methods=await safe(db,`SELECT COALESCE(v.metodo_pago,'efectivo') m,COUNT(*) n,COALESCE(SUM(v.total),0) s FROM ventas v WHERE DATE(v.created_at) BETWEEN ? AND ? AND v.estado_venta='registrada'${bs} GROUP BY v.metodo_pago ORDER BY s DESC`,[from,to,...bp],[]);
    const itemBranch=branch?' AND COALESCE(vi.sucursal_id,p.sucursal_id,v.sucursal_id)=?':'';
    const top=await safe(db,`SELECT p.nombre,SUM(vi.cantidad) cant,COALESCE(SUM(vi.subtotal),0) s FROM venta_items vi JOIN ventas v ON v.id=vi.venta_id JOIN productos p ON p.id=vi.producto_id WHERE DATE(v.created_at) BETWEEN ? AND ? AND v.estado_venta='registrada'${itemBranch} GROUP BY p.id,p.nombre ORDER BY cant DESC LIMIT 8`,[from,to,...bp],[]);
    const byBranch=global&&!branch?await safe(db,`SELECT s.id,s.nombre,COUNT(v.id) n,COALESCE(SUM(v.total),0) total FROM sucursales s LEFT JOIN ventas v ON v.sucursal_id=s.id AND v.estado_venta='registrada' AND DATE(v.created_at) BETWEEN ? AND ? WHERE s.estado=0 GROUP BY s.id,s.nombre ORDER BY total DESC`,[from,to],[]):[];
    const low=await safe(db,`SELECT p.nombre,p.stock_actual,p.stock_minimo,s.nombre sucursal_nombre FROM productos p LEFT JOIN sucursales s ON s.id=p.sucursal_id WHERE p.estado=0 AND p.stock_actual<=p.stock_minimo${productWhere} ORDER BY (p.stock_actual-p.stock_minimo),p.nombre LIMIT 8`,branch?[branch]:[],[]);
    const latest=await safe(db,`SELECT v.id,v.numero,v.total,v.tipo_comprobante,DATE_FORMAT(v.created_at,'%Y-%m-%dT%H:%i:%s') created_at,COALESCE(NULLIF(c.razon_social,''),NULLIF(TRIM(CONCAT_WS(' ',c.nombre,c.apellido_paterno,c.apellido_materno)),''),NULLIF(v.cliente_web_nombre,''),'Cliente General') cliente_nombre,s.nombre sucursal_nombre FROM ventas v LEFT JOIN clientes c ON c.id=v.cliente_id LEFT JOIN sucursales s ON s.id=v.sucursal_id WHERE v.estado_venta='registrada'${bs} ORDER BY v.id DESC LIMIT 8`,bp,[]);
    const [channels,hours,quoteRows,deliveryRows,receiptRows,cashRows] = await Promise.all([
      safe(db,`SELECT CASE WHEN LOWER(COALESCE(v.canal,'')) IN ('web','ecommerce') OR v.pedido_web_id IS NOT NULL THEN 'web' ELSE 'presencial' END canal,COUNT(*) n,COALESCE(SUM(v.total),0) total FROM ventas v WHERE DATE(v.created_at) BETWEEN ? AND ? AND v.estado_venta='registrada'${bs} GROUP BY canal`,[from,to,...bp],[]),
      safe(db,`SELECT HOUR(v.created_at) hora,COUNT(*) n,COALESCE(SUM(v.total),0) total FROM ventas v WHERE DATE(v.created_at) BETWEEN ? AND ? AND v.estado_venta='registrada'${bs} GROUP BY HOUR(v.created_at) ORDER BY hora`,[from,to,...bp],[]),
      safe(db,`SELECT COUNT(*) total,SUM(CASE WHEN estado='convertida' THEN 1 ELSE 0 END) convertidas,SUM(CASE WHEN estado='vigente' AND vence_at>=NOW() THEN 1 ELSE 0 END) vigentes,SUM(CASE WHEN estado='vigente' AND vence_at<NOW() THEN 1 ELSE 0 END) vencidas FROM cotizaciones c WHERE DATE(c.created_at) BETWEEN ? AND ?${branch?' AND c.sucursal_id=?':''}`,[from,to,...bp],[{total:0,convertidas:0,vigentes:0,vencidas:0}]),
      safe(db,`SELECT COUNT(*) total,SUM(estado IN ('pendiente','preparando','listo','asignado','en_ruta')) activas,SUM(estado='entregado') entregadas,SUM(estado IN ('incidencia','observado','no_entregado')) incidencias FROM pedido_entregas_sucursal pes WHERE DATE(pes.created_at) BETWEEN ? AND ?${branch?' AND pes.sucursal_id=?':''}`,[from,to,...bp],[{total:0,activas:0,entregadas:0,incidencias:0}]),
      safe(db,`SELECT COUNT(*) total,SUM(estado_sunat IN ('pendiente','observado','error')) revisar,SUM(estado_sunat='aceptado') aceptados FROM ventas v WHERE DATE(v.created_at) BETWEEN ? AND ? AND v.estado_venta='registrada' AND v.tipo_comprobante IN ('boleta','factura')${bs}`,[from,to,...bp],[{total:0,revisar:0,aceptados:0}]),
      safe(db,`SELECT COUNT(*) turnos,SUM(estado='abierta') abiertas,COALESCE(SUM(CASE WHEN estado<>'abierta' THEN ABS(COALESCE(monto_final,0)-(COALESCE(monto_inicial,0)+COALESCE(total_ventas,0)+COALESCE(total_ingresos,0)-COALESCE(total_egresos,0))) ELSE 0 END),0) diferencia FROM caja_sesiones cs WHERE DATE(cs.abierta_at) BETWEEN ? AND ?${branch?' AND cs.sucursal_id=?':''}`,[from,to,...bp],[{turnos:0,abiertas:0,diferencia:0}])
    ]);
    let profitability=null;if(await hasPermission(req,'dashboard.ver_costos')){const pr=(await safe(db,`SELECT COALESCE(SUM(GREATEST(0,vi.subtotal)),0) ingresos,COALESCE(SUM(LEAST(GREATEST(0,vi.subtotal),GREATEST(0,vi.cantidad*COALESCE(NULLIF(vi.costo_unitario,0),p.precio_costo,0)))),0) costo,SUM(CASE WHEN vi.cantidad*COALESCE(NULLIF(vi.costo_unitario,0),p.precio_costo,0)>GREATEST(0,vi.subtotal) THEN 1 ELSE 0 END) inconsistencias FROM venta_items vi JOIN ventas v ON v.id=vi.venta_id LEFT JOIN productos p ON p.id=vi.producto_id WHERE DATE(v.created_at) BETWEEN ? AND ? AND v.estado_venta='registrada'${itemBranch}`,[from,to,...bp],[{ingresos:0,costo:0,inconsistencias:0}]))[0]||{};const i=Number(pr.ingresos||0),c=Math.min(i,Number(pr.costo||0)),m=Math.max(0,i-c);profitability={ingresos:i,costo:c,margen_bruto:m,margen_pct:i?(m/i)*100:0,egresos:null,resultado_estimado:null,inconsistencias:Number(pr.inconsistencias||0),nota:Number(pr.inconsistencias||0)?'Se limitaron costos inconsistentes al importe vendido. Revísalos en Rentabilidad.':'Margen estimado según el costo histórico de cada venta.'};}
    const cur=Number(period.s||0),old=Number(prev.s||0);res.json({ok:true,esGlobal:global,sucursalId:branch,periodo:{desde:from,hasta:to,anterior_desde:previousFrom,anterior_hasta:previousTo},permisos:{costos:!!profitability,finanzas:await hasPermission(req,'dashboard.ver_finanzas')},kpis:{ventasHoyMonto:Number(day.s||0),ventasHoyCount:Number(day.n||0),ventasMesMonto:cur,ventasMesCount:Number(period.n||0),ticketPromedio:Number(period.n)?cur/Number(period.n):0,variacionVentas:old?((cur-old)/old)*100:(cur?100:0),productos:Number(product.n||0),stockBajo:Number(product.low||0),clientes:Number(clients.n||0),pagosPendientes:Number(pending.n||0),cotizaciones:Number(quoteRows[0]?.total||0),conversionCotizaciones:Number(quoteRows[0]?.total||0)?100*Number(quoteRows[0]?.convertidas||0)/Number(quoteRows[0]?.total||0):0,entregasActivas:Number(deliveryRows[0]?.activas||0),incidenciasEntrega:Number(deliveryRows[0]?.incidencias||0),comprobantesRevisar:Number(receiptRows[0]?.revisar||0),cajasAbiertas:Number(cashRows[0]?.abiertas||0)},serie14:series,metodos:methods,canales:channels,horas:hours,cotizaciones:quoteRows[0]||{},entregas:deliveryRows[0]||{},comprobantes:receiptRows[0]||{},caja:cashRows[0]||{},topProductos:top,porSucursal:byBranch,stockBajoLista:low,ultimasVentas:latest,rentabilidad:profitability});
  })
};
